### ISSUE TITLE
LlaMA 2: Input prompt (2664 tokens) is too long and exceeds limit of 2048/2560

### ISSUE THREAD

**Issue by foamliu** [vllm-project/vllm#525]
As we all know, LlaMA 2 can support a maximum context length of 4096 tokens, but the current code will report an warning then return empty string:
```
CompletionOutput(index=0, text='', token_ids=[], cumulative_logprob=0.0, logprobs=[], finish_reason=length)
```

**Comment by LiuXiaoxuanPKU** [comment]
Could you double check you are using the latest version of vllm?

**Comment by irasin** [comment]
Hi @foamliu. I think you may need to set `max_num_batched_tokens` to at least 4096 to support llama2 model max_seq_length， because the default value of `max_num_batched_tokens` is 2560 in EngineArgs.

**Comment by foamliu** [comment]
> Could you double check you are using the latest version of vllm? We fixed a bug about sequence length recently #489. Also, we haven't finished the support for LLaMA2, please keep an eye on #505.

Big thanks to the super awesome vllm project team, I'll try the latest version and update here.

**Comment by tjedwards** [comment]
It turns out this is a bug in the Llama-2 config.json.  The updated config.json eliminates `max_length` and sets `max_position_embeddings` to 4096.

**Comment by HarrisonBT** [comment]
WARNING 07-28 03:23:18 scheduler.py:196] Input prompt (2716 tokens) is too long and exceeds limit of 4096

**Comment by zhuohan123** [comment]
> 

There is a logging error over here: https://github.com/vllm-project/vllm/blob/64f23c29000ca832f50d3470a83d7a9bdbe95a0c/vllm/core/scheduler.py#L196-L198

We will fix it!

**Comment by robcaulk** [comment]
This should be fixed now upstream:

https://huggingface.co/WizardLM/WizardLM-13B-V1.2/discussions/24#64f2f5518a8ea36896f1e26a

**Comment by alekhya14** [comment]
I am still facing this issue. I am using vllm v 0.1.7
getting this error: Input prompt (3412 tokens) is too long and exceeds limit of 2560

Is there something I am missing out?

**Comment by khadkechetan** [comment]
I am also facing the same issue. any help would be appreciated.

**Comment by yuanxiaobin876-cn** [comment]
vllm源码中的判断是这样的
                if num_prompt_tokens > min(
                        self.scheduler_config.max_model_len,
                        self.scheduler_config.max_num_batched_tokens):
                    logger.warning(
                        f"Input prompt ({num_prompt_tokens} tokens) is too long"
                        " and exceeds limit of "
                        f"{self.scheduler_config.max_model_len}")
通过max_model_len参数和max_num_batched_tokends参数配置到合适的值就可以规避这个问题

**Comment by ZhuoerFeng** [comment]
Hero. Helped me a lot. I met the problem in Xinference + vLLM core. A glm-4-9b-chat with context window over 120k is cut under 4096.

**Comment by lldxflwb** [comment]
> vllm源码中的判断是这样的 if num_prompt_tokens > min( self.scheduler_config.max_model_len, self.scheduler_config.max_num_batched_tokens): logger.warning( f"Input prompt ({num_prompt_tokens} tokens) is too long" " and exceeds limit of " f"{self.scheduler_config.max_model_len}") 通过max_model_len参数和max_num_batched_tokends参数配置到合适的值就可以规避这个问题

真好，你的这个回复完美的解决了我的问题，我部署一个deepseek r1 671b满血版，输入token被限制在了2k，真的是匪夷所思
