### ISSUE TITLE
vLLM stops all processing when CPU KV cache is used, has to be shut down and restarted.

### ISSUE THREAD

**Issue by TheBloke** [vllm-project/vllm#546]
Hi

The issue: with `--swap-space X` specified, as soon as CPU KV cache is used, vLLM stops all processing.  CPU and GPU usage go to 0%, and the request never returns. Any future requests are also never answered.  There is no error.

I am testing the latest vLLM code (commit  6fc2a38) in a Docker container.  I have experienced the issue since I first started using vLLM about 4 days ago, so it's not specific to the latest commits.

I am launching vLLM with the following args:
```
--model lmsys/vicuna-7b-v1.3 --host 0.0.0.0 --tokenizer hf-internal-testing/llama-tokenizer --swap-space 100 
```

I am currently testing on a 1 x 4090 system, but I have experienced it on all GPU types I've tried, including A6000 and H100.

The following test code will quickly trigger the issue on a 1 x 4090 system:

```python
import time
import requests

url = 'http://localhost:8000/v1/completions'
headers = {'Content-Type': 'application/json'}
data = {
    "model": "lmsys/vicuna-7b-v1.3",
    "prompt": " Write a story about a cat named George."*40,
    "max_tokens": 950,
    "temperature": 0.7,
    "n":125
}
s=time.time()
response = requests.post(url, headers=headers, json=data)
print(time.time()-s)
```

Here's a screenshot demonstrating the issue:
<img width="1635" alt="image" src="https://github.com/vllm-project/vllm/assets/784313/d147be60-a604-4210-a2fd-e9853855d26b">

In the screenshot you can see that only 7.9% of CPU KV cache is used, but this is enough to cause all processing to stop.  The server will now never answer this request, and never answer any new requests either. It is effectively dead.

If I leave out `--swap-space X` then the server aborts `RuntimeError: Aborted due to the lack of CPU swap space. Please increase the swap space to avoid this error.`, which is what I'm trying to avoid.  It would be nice to be able to use CPU RAM as an overflow buffer, in case I occasionally exceed VRAM.

Thanks in advance.

**Comment by Lawliet-Xie** [comment]
I had the same problem, did you solve it？

**Comment by TheBloke** [comment]
No, I'm not sure it's something we can solve ourselves.  Might need a code fix.

**Comment by syskn** [comment]
Might be related: https://github.com/vllm-project/vllm/issues/667

**Comment by desperadoola** [comment]
https://github.com/vllm-project/vllm/blob/66c54aa9c33555a6b41421d57d3ad6c1bf004ec9/vllm/engine/async_llm_engine.py#L67-L75

I comment this `await asyncio.sleep(0)` and it seems to temporarily solve the stuck.

**Comment by SatoshiReport** [comment]
Same issue.  Cache fills up and then vLLM stops working.

**Comment by tydia** [comment]
this issue makes vllm impossible for production use

**Comment by chi2liu** [comment]
> this issue makes vllm impossible for production use

At present, we have found a workaround and set the swap space directly to 0. This way, we will not call the CPU swap space and will not report any errors. However, the CPU blocks will also become 0, which may slow down the speed a bit, but at least it will not hang and die.

**Comment by hmellor** [comment]
@TheBloke are you still experiencing this issue?

**Comment by shyringo** [comment]
> > this issue makes vllm impossible for production use
> 
> At present, we have found a workaround and set the swap space directly to 0. This way, we will not call the CPU swap space and will not report any errors. However, the CPU blocks will also become 0, which may slow down the speed a bit, but at least it will not hang and die.

Wondering how can I set the swap space directly to 0?

**Comment by hmellor** [comment]
`--swap-space 0` - [docs](https://docs.vllm.ai/en/latest/models/engine_args.html)

**Comment by haoxiongliu** [comment]
> > this issue makes vllm impossible for production use
> 
> At present, we have found a workaround and set the swap space directly to 0. This way, we will not call the CPU swap space and will not report any errors. However, the CPU blocks will also become 0, which may slow down the speed a bit, but at least it will not hang and die.


When using vllm 0.5.1, setting swap_space=0 will cause the process to terminate despite # CPU blocks being 0.

`ERROR 07-11 00:49:14 async_llm_engine.py:53]     self._preempt_by_swap(seq_group, blocks_to_swap_out)
ERROR 07-11 00:49:14 async_llm_engine.py:53]   File "/opt/miniconda3/envs/working/lib/python3.11/site-packages/vllm/core/scheduler.py", line 1145, in _preempt_by_swap
ERROR 07-11 00:49:14 async_llm_engine.py:53]     self._swap_out(seq_group, blocks_to_swap_out)
ERROR 07-11 00:49:14 async_llm_engine.py:53]   File "/opt/miniconda3/envs/working/lib/python3.11/site-packages/vllm/core/scheduler.py", line 1165, in _swap_out
ERROR 07-11 00:49:14 async_llm_engine.py:53] RuntimeError: Aborted due to the lack of CPU swap space. Please increase the swap space to avoid this error.`

**Comment by hmellor** [comment]
Potentially this is a bug that's been fixed in `BlockSpaceMangerV2`?

You can enable it using `--use-v2-block-manager`

**Comment by haoxiongliu** [comment]
> I see two workarounds being discussed for this thread:
> 
> 1. Setting `--swap-space to 0`, but according to @haoxiongliu from version >= 0.5.1 setting swap_space=0 cause the process to terminate once vllm preempt a sequence group. @haoxiongliu can you confirm if you face the  `_preempt_by_swap ERROR` even in the latest versions?
> 2. @hmellor Were you able to verify if this bug exists after `--use-v2-block-manager` in the latest versions?

It still happens no matter whether `--use-v2-block-manager` is set in vllm 0.6.3.
```
INFO 10-28 11:16:34 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7220.5 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 98 reqs, GPU KV cache usage: 73.8%, CPU KV cache usage: 0.0%.
INFO 10-28 11:16:39 metrics.py:349] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 7154.5 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 98 reqs, GPU KV cache usage: 86.1%, CPU KV cache usage: 0.0%.
WARNING 10-28 11:16:41 scheduler.py:1483] Sequence group chat-7e630abf1a8b4c8a88775b1e98a54cf2 is preempted by PreemptionMode.SWAP mode because there is not enough KV cache space. This can affect the end-to-end performance. Increase gpu_memory_utilization or tensor_parallel_size to provide more KV cache memory. total_num_cumulative_preemption=1
ERROR 10-28 11:16:41 engine.py:158] RuntimeError('Aborted due to the lack of CPU swap space. Please increase the swap space to avoid this error.')
ERROR 10-28 11:16:41 engine.py:158] Traceback (most recent call last):
ERROR 10-28 11:16:41 engine.py:158]   File "/home/user/miniconda3/envs/working/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 156, in start
ERROR 10-28 11:16:41 engine.py:158]     self.run_engine_loop()
ERROR 10-28 11:16:41 engine.py:158]   File "/home/user/miniconda3/envs/working/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 219, in run_engine_loop
ERROR 10-28 11:16:41 engine.py:158]     request_outputs = self.engine_step()
ERROR 10-28 11:16:41 engine.py:158]                       ^^^^^^^^^^^^^^^^^^
ERROR 10-28 11:16:41 engine.py:158]   File "/home/user/miniconda3/envs/working/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 237, in engine_step
ERROR 10-28 11:16:41 engine.py:158]     raise e
ERROR 10-28 11:16:41 engine.py:158]   File "/home/user/miniconda3/envs/working/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 228, in engine_step
ERROR 10-28 11:16:41 engine.py:158]     return self.engine.step()
ERROR 10-28 11:16:41 engine.py:158]            ^^^^^^^^^^^^^^^^^^
ERROR 10-28 11:16:41 engine.py:158]   File "/home/user/miniconda3/envs/working/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 1342, in step
ERROR 10-28 11:16:41 engine.py:158]     ) = self.scheduler[virtual_engine].schedule()
ERROR 10-28 11:16:41 engine.py:158]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-28 11:16:41 engine.py:158]   File "/home/user/miniconda3/envs/working/lib/python3.11/site-packages/vllm/core/scheduler.py", line 1219, in schedule
ERROR 10-28 11:16:41 engine.py:158]     scheduler_outputs: SchedulerOutputs = self._schedule()
ERROR 10-28 11:16:41 engine.py:158]                                           ^^^^^^^^^^^^^^^^
ERROR 10-28 11:16:41 engine.py:158]   File "/home/user/miniconda3/envs/working/lib/python3.11/site-packages/vllm/core/scheduler.py", line 1178, in _schedule
ERROR 10-28 11:16:41 engine.py:158]     return self._schedule_default()
ERROR 10-28 11:16:41 engine.py:158]            ^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-28 11:16:41 engine.py:158]   File "/home/user/miniconda3/envs/working/lib/python3.11/site-packages/vllm/core/scheduler.py", line 1025, in _schedule_default
ERROR 10-28 11:16:41 engine.py:158]     running_scheduled = self._schedule_running(budget,
ERROR 10-28 11:16:41 engine.py:158]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-28 11:16:41 engine.py:158]   File "/home/user/miniconda3/envs/working/lib/python3.11/site-packages/vllm/core/scheduler.py", line 604, in _schedule_running
ERROR 10-28 11:16:41 engine.py:158]     preempted_mode = self._preempt(victim_seq_group,
ERROR 10-28 11:16:41 engine.py:158]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 10-28 11:16:41 engine.py:158]   File "/home/user/miniconda3/envs/working/lib/python3.11/site-packages/vllm/core/scheduler.py", line 1495, in _preempt
ERROR 10-28 11:16:41 engine.py:158]     self._preempt_by_swap(seq_group, blocks_to_swap_out)
ERROR 10-28 11:16:41 engine.py:158]   File "/home/user/miniconda3/envs/working/lib/python3.11/site-packages/vllm/core/scheduler.py", line 1516, in _preempt_by_swap
ERROR 10-28 11:16:41 engine.py:158]     self._swap_out(seq_group, blocks_to_swap_out)
ERROR 10-28 11:16:41 engine.py:158]   File "/home/user/miniconda3/envs/working/lib/python3.11/site-packages/vllm/core/scheduler.py", line 1536, in _swap_out
ERROR 10-28 11:16:41 engine.py:158]     raise RuntimeError(
ERROR 10-28 11:16:41 engine.py:158] RuntimeError: Aborted due to the lack of CPU swap space. Please increase the swap space to avoid this error.
```

**Comment by bilzard** [comment]
I don't know if it helps, but making prompt token length short solves my case.

- The original maximum prompt characters: 4103 (mean=1458)
- The shortened maximum prompt characters: 3483 (mean=838)

vllm version=`0.5.3.post1`

**Comment by robertgshaw2-redhat** [comment]
Closing since we are addressing this in V1
